name: Lint

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install lint tools
        run: python -m pip install --upgrade pip black ruff
      - name: Ruff
        run: ruff check crstlmeth tests
      - name: Black check
        run: black --check crstlmeth tests
